
model:
  beta:      1.0
  ntau:      8
  hz:        1.0
  mu:        1.0 
  h:         0.02
  U:         0.80
  gamma:     0.0

simulation:
  dt:          0.0005
  stepsize:    0.001
  ntmax:       50000
  io_interval: 100
  noise:       true
  seed:  0
  isPlotting:  True
  ETOL:    0.0001
  max_iters:    500
  print_iters:   True
