
model:
  beta:      1.0
  ntau:      8
  hz:        0.4
  mu:        1.0 
  h:         0.02
  U:         0.80
  gamma:     1.40

simulation:
  dt:          0.025
  stepsize:    0.001
  ntmax:       50000
  io_interval: 500
  noise:       true
  seed:  0
  isPlotting:  True
  ETOL:    0.000001
  max_iters:    500
  print_iters:   True
