
model:
  beta:      1.0
  ntau:      12
  hz:        0.2
  mu:        1.0 
  h:         0.02
  U:         0.00
  gamma:     0.25

simulation:
  dt:          0.01
  stepsize:    0.001
  ntmax:       100000
  io_interval: 500
  noise:       true
  seed:  0
  isPlotting:  True
  ETOL:    0.000001
  max_iters:    500
  print_iters:   True
