
model:
  beta:      0.125
  mu:        1.0 
  h:         0.02
  gamma:     0.0 

timestepping:
  dt:          0.0005
  ntmax:       1000000
  io_interval: 1000
  noise:       true
  seed:  0
  isPlotting:  false
  lambda_psi:  0.1


simulation:
  stepsize:     0.1
  ETOL:         0.01
  max_iters:    500
  print_iters:  false 
